const blogContents = [
    { 
        title: "AutoML vs. Humans:", 
        subtitle: "Are Data Scientists Still Needed?",
        description: `Google's machine learning platform, Vertex AI, 
        has introduced AutoML, which automatically selects and tunes machine learning models. 
        Particularly for structured data, there is a service called AutoML Tables, 
        which allows anyone to easily build and analyse machine learning models. In some cases, 
        it can generate highly accurate models, and it has even achieved second place in a Kaggle competition. 
        However, this raises several questions. When analysing actual business data, 
        are the models generated by AutoML Tables better than those created by humans? `,
        image: "images/aivshuman.png"
    },
    { 
        title: "Enabling a Large Number of Image Processing", 
        subtitle: "Understanding Memory Overflow Solutions",
        description: `I was in charge of implementing the image hosting system at CyberOwl. 
        During this process, it was discovered that when the Ruby on Rails server performed a large number of image edits simultaneously, 
        it led to a memory overflow. To address this issue, semaphores were utilised. 
        In addition to discussing this solution, this article compiles the necessary knowledge about processes, 
        threads, semaphores, mutex, and how the Rails web server puma handles multiple requests.`,
        image: "images/rails.png"
    },
    { title: "Card 3", description: "This is the first card." },
    { title: "Card 4", description: "This is the second card." },
];

export default blogContents;